services:
  chroma_db:
    image: chromadb/chroma:0.6.4.dev226
    container_name: chroma_db
    volumes:
      - chroma_db_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama_llm:
    image: ollama/ollama:latest
    container_name: ollama_llm
    volumes:
      - ollama_llm_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama run gemma3:1b && wait"]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/11434" ]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama_embedding:
    image: ollama/ollama:latest
    container_name: ollama_embedding
    volumes:
        - ollama_embedding_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11435
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull nomic-embed-text && wait"]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/11435" ]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
    ports:
      - "${API_PORT:-5000}:5000"
    env_file:
      - .env
    depends_on:
      chroma_db:
        condition: service_healthy
      ollama_llm:
        condition: service_healthy
      ollama_embedding:
        condition: service_healthy


volumes:
  chroma_db_data:
  ollama_llm_data:
  ollama_embedding_data: